<?php

namespace Travian\HTMLSax3;

class StateParserGtet430 extends StateParser
{
    public function __construct(&$htmlsax)
    {
        parent::__construct($htmlsax);
        $this->parser_options['XML_OPTION_TRIM_DATA_NODES'] = 0;
        $this->parser_options['XML_OPTION_CASE_FOLDING'] = 0;
        $this->parser_options['XML_OPTION_LINEFEED_BREAK'] = 0;
        $this->parser_options['XML_OPTION_TAB_BREAK'] = 0;
        $this->parser_options['XML_OPTION_ENTITIES_PARSED'] = 0;
        $this->parser_options['XML_OPTION_ENTITIES_UNPARSED'] = 0;
        $this->parser_options['XML_OPTION_STRIP_ESCAPES'] = 0;
    }

    public function parse($data)
    {
        parent::parse($data); // TODO: Change the autogenerated stub
    }

    public function scanUntilCharacters($string)
    {
        $startpos = $this->position;
        $length = strcspn($this->rawtext, $string, $startpos);
        $this->position += $length;
        return substr($this->rawtext, $startpos, $length);
    }

    public function ignoreWhitespace()
    {
        $this->position += strspn($this->rawtext, " \n\r\t", $this->position);
    }

}